spring:
  server:
    port: 8080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gift_certificate_v3
    username: root
    password: 2584170

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
  security:
    oauth2:
      grant-types: password, implicit
      scopes: read, write
      authorities: admin, user
      access-token-validity-seconds: 260000
      signing-key: as466gf
      client:
        id: client
        secret: password